---
- name: >-
    Setup Nginx to proxy to stats app
  hosts: beam
  become: true
  become_user: root
  
  roles:
    - role: nrser.nansi.nginx
  
  tasks:    
    - nrser.nansi.nginx_site:
        name: stats
        server_names:
          - "{{ CORTEX_WEB_HOST }}"
        log_dir: "/var/log/nginx/{{ CORTEX_WEB_HOST }}"
        lets_encrypt: True
        http: redirect
        https: True
        proxy: True
        proxy_port: "{{ CORTEX_WEB_PORT }}"
    
    - nrser.nansi.nginx_site:
        name: "{{ CORTEX_WEB_LINK_URL_HOST }}"
        server_names:
          - "{{ CORTEX_WEB_LINK_URL_HOST }}"
        log_dir: "/var/log/nginx/{{ CORTEX_WEB_LINK_URL_HOST }}"
        lets_encrypt: True
        http: redirect
        https: True
        proxy: True
        proxy_port: "{{ CORTEX_WEB_LINK_HTTP_PORT }}"
