---
- name: >-
    Deploy stats app
  hosts: app
  become: true
  become_user: root
  
  tasks:
    - file:
        path: "{{ APP_DEST }}"
        state: directory
  
    - ansible.builtin.unarchive:
        src: "../../../rel/artifacts/{{ APP_NAME }}-{{ APP_VERSION }}.tar.gz"
        dest: "{{ APP_DEST }}"
        mode: 0755
        
    - name: >-
        Change owner and group to {{ APP_USER }}:{{ APP_USER }}
      file:
        path: "{{ APP_DEST }}"
        owner: "{{ APP_USER }}"
        group: "{{ APP_USER }}"
            
    