# https://docs.ansible.com/ansible/latest/plugins/inventory/yaml.html
# 
all:
  hosts:
    spf:
      ansible_host: 3.13.82.241
      ansible_user: ubuntu
      # tf_provider: azurerm
      # tf_resource: azurerm_linux_virtual_machine
      
  # Groups
  # ==========================================================================
  # 
  # Hosts are assigned here, variables are assigned in
  # 
  #     @/inventory/group_vars/<group_name>.yaml
  # 
  children:    
    # Operating System Groups
    # ========================================================================
    
    ubuntu:
      hosts:
        spf: {}
    
    # Application Groups
    # ========================================================================
        
    db:
      hosts:
        spf: {}
        
    kafka:
      hosts:
        spf: {}
        
    beam:
      hosts:
        spf: {}
    
    