---
- name: >-
    Install stats app dependencies
  hosts: beam
  become: true
  become_user: root
  
  roles:
    - role: nansi.nginx.support
  
  tasks:
    - tags:
        - nginx
      block:
        - name: Install Nginx
          nansi.nginx.package:
        
        - name: Generate OpenSSL dhparam (so Nginx can use it)
          nansi.nginx.dhparam:
          notify: nginx_restart
        
        - name: Write Nginx config
          nansi.nginx.config:
          notify: nginx_restart
        
        - name: Enable Nginx server
          service:
            name: nginx
            state: started
            enabled: True
  
    - name: Install Erlang
      tags:
        - erlang
      nansi.erlang.package:
        version: 23.2.3
        
    - name: Install Elixir
      tags:
        - elixir
      nansi.elixir.package:
        version: 1.11.2
        
    - name: Install NodeJS
      tags:
        - nodejs
      nansi.nodejs.package:
        version: 14.17.2
