HUMANS:
  - name: nrser
    admin: true
    github: nrser
    git:
      "user.name": nrser
      "user.email": neil@neilsouza.com
    fp_email: neil@futureperfect.studio
  
  - name: xander
    admin: true
    github: xanderseren
    git:
      "user.name": xanderseren
      "user.email": xander@theactualschool.com
    fp_email: xander@futureperfect.studio

APP_NAME: stats
APP_VERSION: 0.1.0

APP_DEST: "/usr/local/experf/{{ APP_NAME }}/{{ APP_VERSION }}"

CORTEX_WEB_HOST: stats.expand.live
CORTEX_WEB_PORT: 4080

CORTEX_WEB_SECRET: >-
  {{
    lookup(
      'community.general.onepassword',
      'Stats -- Cortex Web -- Secret',
      field='password',
      username=(
        HUMANS | nrser.nansi.find_has_all(name=lookup('env', 'USER'))
      ).fp_email,
      subdomain='futureperfectcreativestudio',
    )
  }}

APP_USER: "{{ APP_NAME }}"

DB_NAME: cortex_prod
DB_PASSWORD: >-
  {{
    lookup(
      'community.general.onepassword',
      'Stats -- PostgreSQL',
      field='password',
      username=(
        HUMANS | nrser.nansi.find_has_all(name=lookup('env', 'USER'))
      ).fp_email,
      subdomain='futureperfectcreativestudio',
    )
  }}
DB_HOST: localhost

CORTEX_MAILGUN_DOMAIN: >-
  {{
    lookup(
      'community.general.onepassword',
      'Stats -- Cortex -- Mailgun Sending Key',
      field='username',
      username=(
        HUMANS | nrser.nansi.find_has_all(name=lookup('env', 'USER'))
      ).fp_email,
      subdomain='futureperfectcreativestudio',
    )
  }}

CORTEX_MAILGUN_API_KEY: >-
  {{
    lookup(
      'community.general.onepassword',
      'Stats -- Cortex -- Mailgun Sending Key',
      field='password',
      username=(
        HUMANS | nrser.nansi.find_has_all(name=lookup('env', 'USER'))
      ).fp_email,
      subdomain='futureperfectcreativestudio',
    )
  }}
