---
# Global Variables
# ============================================================================
#
# Variables that (conceptually) span above the Stats system. Eventually, we'd
# like for these to be in some single source of truth (at least, conceptually).
# 

HUMANS:
  - name: nrser
    admin: true
    github: nrser
    git:
      "user.name": nrser
      "user.email": neil@neilsouza.com
    org_email: neil@expand.live
  
  - name: xander
    admin: true
    github: xanderseren
    git:
      "user.name": xanderseren
      "user.email": xander@theactualschool.com
    org_email: xander@expand.live

ONEPASSWORD_SUBDOMAIN: futureperfectcreativestudio
ONEPASSWORD_USERNAME: >-
  (HUMANS | nrser.nansi.find_has_all(name=lookup('env', 'USER'))).org_email

# Controller Variables
# ============================================================================
#
# Variables that relate to the _controller_ host -- the one that you run 
# Ansible commands on (as opposed to the _target_ system being managed). Right
# now (2021-03-04), that means your dev machine.
# 

# The Git repository root directory, which is useful for finding things on the
# controller.
CTL_REPO_ROOT: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"

# System & Shared Variables
# ============================================================================
#
# Variables that are Stats system-wide or shared across multiple components 
# (like database connection credentials).
# 

STATS_NAME: stats
STATS_USER: "{{ STATS_NAME }}"

STATS_DB_NAME: cortex_prod
STATS_DB_PASSWORD: >-
  {{
    lookup(
      'community.general.onepassword',
      'Stats -- PostgreSQL',
      field='password',
      username=ONEPASSWORD_USERNAME,
      subdomain=ONEPASSWORD_SUBDOMAIN,
    )
  }}
STATS_DB_HOST: localhost
