---
- name: >-
    Deploy stats database
  hosts: db
  become: true
  become_user: root
  
  roles:
    - role: nansi.postgres.install
  
  tasks:
    - name: Make sure psycopg2 is installed
      apt:
        name: python3-psycopg2
        state: present
  
    - name: >-
        Create app user `{{ STATS_USER }}`
      user:
        name: "{{ STATS_USER }}"
        state: present
        create_home: false
        shell: /bin/bash
  
    - name: "Create `{{ STATS_DB_NAME }}` database"
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ STATS_DB_NAME }}"
    
    - name: "Add user `{{ STATS_USER }}` to database `{{ STATS_DB_NAME }}`"
      become: true
      become_user: postgres
      postgresql_user:
        db: "{{ STATS_DB_NAME }}"
        name: "{{ STATS_USER }}"
        password: "{{ STATS_DB_PASSWORD }}"
        priv: ALL
  
    - name: "Ensure user `{{ STATS_USER }}` does not have unnecessary privilege"
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ STATS_USER }}"
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    
    - name: "Ensure no other user can access the `{{ STATS_DB_NAME }}` database"
      become: true
      become_user: postgres
      postgresql_privs:
        db: "{{ STATS_DB_NAME }}"
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
    