---
- name: Deploy Kafka to stats servers
  hosts: kafka
  become: true
  become_user: root
  
  tasks:
    - apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
    
    - name: Install Docker CE
      nansi.apt.ext:
        state: present
        key_id: 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
        key_url: https://download.docker.com/linux/ubuntu/gpg
        repository_repo: >-
          deb [arch={arch}] https://download.docker.com/linux/ubuntu {release} stable
        names:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    
    # Resources:
    # 
    # 1.  https://medium.com/better-programming/a-simple-apache-kafka-cluster-with-docker-kafdrop-and-python-cf45ab99e2b9
    # 
    - name: Deploy single-instance Zookeeper
      nansi.systemd.docker_service:
        name: zookeeper
        state: present
        description: Zookeeper (for Kafka)
        tag: "zookeeper:3.6.2"
        config:
          - nansi.copy.serialize:
              data:
                ZOO_MY_ID: 1
                ZOO_SERVERS: server.1=0.0.0.0:2888:2889;2181
              format: env
              dest: "{config}/.env"
              mode: '0600'
        opts:
          hostname: zookeeper
          network: host
          volume:
            - "zookeeper-data:/data:rw"
            - "zookeeper-datalog:/datalog:rw"
          env-file: "{config}/.env"
  
    - name: Deploy single-instance Kafka
      nansi.systemd.docker_service:
        name: kafka
        state: present
        description: Kafka Broker
        tag: "confluentinc/cp-kafka:5.5.3"
        requires:
          - zookeeper.service
        config:
          - nansi.copy.serialize:
              data:
                KAFKA_ADVERTISED_LISTENERS: LISTENER_HOST_NETWORK://127.0.0.1:9091
                KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_HOST_NETWORK:PLAINTEXT
                KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_HOST_NETWORK
                KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
                KAFKA_BROKER_ID: 1
                KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
              format: env
              dest: "{config}/.env"
              mode: '0600'
        opts:
          hostname: kafka
          network: host
          volume:
            - "kafka-data:/var/lib/kafka/data:rw"
          env-file: "{config}/.env"
